INSERT INTO lms.permissions (id, name, description, date_created)
VALUES (1, 'READ_ROLES', 'can read roles', CURRENT_TIMESTAMP),
       (2, 'WRITE_ROLES', 'can create or update roles', CURRENT_TIMESTAMP),
       (3, 'DELETE_ROLES', 'can delete roles', CURRENT_TIMESTAMP),
       (4, 'READ_USERS', 'can read users', CURRENT_TIMESTAMP),
       (5, 'WRITE_USERS', 'can create or update users', CURRENT_TIMESTAMP),
       (6, 'DELETE_USERS', 'can delete users', CURRENT_TIMESTAMP),
       (7, 'LOGIN', 'can login', CURRENT_TIMESTAMP),
       (8, 'READ_ACCOUNTS', 'can read accounts', CURRENT_TIMESTAMP),
       (9, 'WRITE_ACCOUNTS', 'can create or update accounts', CURRENT_TIMESTAMP),
       (10, 'DELETE_ACCOUNTS', 'can delete accounts', CURRENT_TIMESTAMP),
       (11, 'READ_ACCOUNT_BALANCES', 'can read account balances', CURRENT_TIMESTAMP),
       (12, 'WRITE_ACCOUNT_BALANCES', 'can create or update account balances', CURRENT_TIMESTAMP),
       (13, 'DELETE_ACCOUNT_BALANCES', 'can delete account balances', CURRENT_TIMESTAMP),
       (14, 'READ_ACCOUNT_STATUSES', 'can read account statuses', CURRENT_TIMESTAMP),
       (15, 'WRITE_ACCOUNT_STATUSES', 'can create or update account statuses', CURRENT_TIMESTAMP),
       (16, 'DELETE_ACCOUNT_STATUSES', 'can delete account statuses', CURRENT_TIMESTAMP),
       (17, 'READ_ACCOUNT_TYPES', 'can read account types', CURRENT_TIMESTAMP),
       (18, 'WRITE_ACCOUNT_TYPES', 'can create or update account types', CURRENT_TIMESTAMP),
       (19, 'DELETE_ACCOUNT_TYPES', 'can delete account types', CURRENT_TIMESTAMP),
       (20, 'READ_CURRENCIES', 'can read currencies', CURRENT_TIMESTAMP),
       (21, 'WRITE_CURRENCIES', 'can create or update currencies', CURRENT_TIMESTAMP),
       (22, 'DELETE_CURRENCIES', 'can delete currencies', CURRENT_TIMESTAMP),
       (23, 'READ_PARTNER_ACCOUNTS', 'can read partner accounts', CURRENT_TIMESTAMP),
       (24, 'WRITE_PARTNER_ACCOUNTS', 'can create or update partner accounts', CURRENT_TIMESTAMP),
       (25, 'DELETE_PARTNER_ACCOUNTS', 'can delete partner accounts', CURRENT_TIMESTAMP),
       (26, 'READ_CREDENTIALS', 'can read credentials', CURRENT_TIMESTAMP),
       (27, 'WRITE_CREDENTIALS', 'can create or update credentials', CURRENT_TIMESTAMP),
       (28, 'DELETE_CREDENTIALS', 'can delete credentials', CURRENT_TIMESTAMP),
       (29, 'READ_LOGIN_ATTEMPTS', 'can read login attempts', CURRENT_TIMESTAMP),
       (30, 'WRITE_LOGIN_ATTEMPTS', 'can create or update login attempts', CURRENT_TIMESTAMP),
       (31, 'DELETE_LOGIN_ATTEMPTS', 'can delete login attempts', CURRENT_TIMESTAMP),
       (32, 'READ_TRANSACTION_TYPES', 'can read transaction types', CURRENT_TIMESTAMP),
       (33, 'WRITE_TRANSACTION_TYPES', 'can create or update transaction types', CURRENT_TIMESTAMP),
       (34, 'DELETE_TRANSACTION_TYPES', 'can delete transaction types', CURRENT_TIMESTAMP),
       (35, 'READ_TRANSACTION_TYPE_COMPONENTS', 'can read transaction type components', CURRENT_TIMESTAMP),
       (36, 'WRITE_TRANSACTION_TYPE_COMPONENTS', 'can create or update transaction type components', CURRENT_TIMESTAMP),
       (37, 'DELETE_TRANSACTION_TYPE_COMPONENTS', 'can delete transaction type components', CURRENT_TIMESTAMP),
       (38, 'READ_TRANSACTIONS', 'can read transactions', CURRENT_TIMESTAMP),
       (39, 'WRITE_TRANSACTIONS', 'can create or update transactions', CURRENT_TIMESTAMP),
       (40, 'DELETE_TRANSACTIONS', 'can delete transactions', CURRENT_TIMESTAMP),
       (41, 'READ_TRANSACTION_ENTRIES', 'can read transaction entries', CURRENT_TIMESTAMP),
       (42, 'WRITE_TRANSACTION_ENTRIES', 'can create or update transaction entries', CURRENT_TIMESTAMP),
       (43, 'DELETE_TRANSACTION_ENTRIES', 'can delete transaction entries', CURRENT_TIMESTAMP);;