DROP SCHEMA IF EXISTS lms CASCADE;;
CREATE SCHEMA lms;;

CREATE TYPE lms.TERM_UNIT AS ENUM ('D','W','M','Y');;
CREATE TYPE lms.ENTITY_TYPE AS ENUM ('CUSTOMER','PARTNER','API_USER','INTERNAL_USER','SYSTEM');;
CREATE TYPE LOAN_STATUS AS ENUM ('PENDING','APPROVED','ACTIVE','PAID_OFF','DEFAULTED','CLOSED','CANCELLED','WRITTEN_OFF');;

CREATE TABLE lms.audit_log (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_name      TEXT                                   NOT NULL,
    record_id       TEXT                                   NOT NULL,
    operation_type  TEXT                                   NOT NULL,
    changed_at      TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    changed_by      TEXT                                   NOT NULL,
    original_values JSONB                                  NOT NULL,
    new_values      JSONB                                  NOT NULL
);;

CREATE TABLE lms.permissions (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         TEXT                     NOT NULL UNIQUE,
    description  TEXT                     NOT NULL,
    version BIGINT DEFAULT 1 NOT NULL,
    date_created TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    date_updated TIMESTAMP WITH TIME ZONE
);;

CREATE TABLE lms.roles (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         TEXT                     NOT NULL UNIQUE,
    description  TEXT                     NOT NULL,
    version BIGINT DEFAULT 1 NOT NULL,
    date_created TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    date_updated TIMESTAMP WITH TIME ZONE
);;

CREATE TABLE lms.role_permissions (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id       BIGINT                   NOT NULL REFERENCES lms.roles ON UPDATE RESTRICT ON DELETE CASCADE,
    permission_id BIGINT                   NOT NULL REFERENCES lms.permissions ON UPDATE RESTRICT ON DELETE CASCADE,
    version      BIGINT                            DEFAULT 1 NOT NULL,
    date_created TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    date_updated  TIMESTAMP WITH TIME ZONE,
    CONSTRAINT unique_role_permission UNIQUE (role_id, permission_id)
);;

CREATE INDEX index_role_permissions_role_id ON lms.role_permissions (role_id);;
CREATE INDEX index_role_permissions_permission_id ON lms.role_permissions (permission_id);;

CREATE TABLE lms.id_types (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         TEXT                     NOT NULL UNIQUE,
    description  TEXT                     NOT NULL,
    version BIGINT DEFAULT 1 NOT NULL,
    date_created TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    date_updated TIMESTAMP WITH TIME ZONE
);;

CREATE TABLE lms.credential_statuses (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         TEXT                     NOT NULL UNIQUE,
    description  TEXT                     NOT NULL,
    version BIGINT DEFAULT 1 NOT NULL,
    date_created TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    date_updated TIMESTAMP WITH TIME ZONE
);;

CREATE TABLE lms.entities (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         TEXT                     NOT NULL,
    entity_type  lms.ENTITY_TYPE          NOT NULL,
    version BIGINT DEFAULT 1 NOT NULL,
    date_created TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    date_updated TIMESTAMP WITH TIME ZONE
);;

CREATE TABLE lms.entity_contacts (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    contact      TEXT                     NOT NULL UNIQUE,
    entity_id    BIGINT REFERENCES lms.entities ON UPDATE RESTRICT ON DELETE CASCADE,
    is_primary   BOOLEAN                  NOT NULL,
    contact_type TEXT                     NOT NULL CHECK (contact_type IN ('EMAIL', 'PHONE')),
    version BIGINT DEFAULT 1 NOT NULL,
    date_created TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    date_updated TIMESTAMP WITH TIME ZONE
);;

CREATE TABLE lms.entity_ids (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_number    TEXT                     NOT NULL,
    id_type      BIGINT                   NOT NULL REFERENCES lms.id_types ON UPDATE RESTRICT ON DELETE RESTRICT,
    entity_id    BIGINT                   NOT NULL REFERENCES lms.entities ON UPDATE RESTRICT ON DELETE CASCADE,
    version BIGINT DEFAULT 1 NOT NULL,
    date_created TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    date_updated TIMESTAMP WITH TIME ZONE,
    CONSTRAINT unique_entity_id UNIQUE (id_number, id_type, entity_id)
);;

CREATE INDEX index_entity_ids_id_number ON lms.entity_ids (id_number);;

CREATE TABLE lms.entity_credentials (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_id             BIGINT                   NOT NULL REFERENCES lms.entities ON UPDATE RESTRICT ON DELETE CASCADE,
    hashed_password       TEXT                     NOT NULL,
    credentials_status_id BIGINT                   NOT NULL REFERENCES lms.credential_statuses ON UPDATE RESTRICT ON DELETE RESTRICT,
    version      BIGINT                            DEFAULT 1 NOT NULL,
    date_created TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    date_updated          TIMESTAMP WITH TIME ZONE
);;

CREATE TABLE lms.login_attempts (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      TEXT                     NOT NULL,
    entity_id     BIGINT                   REFERENCES lms.entities ON UPDATE RESTRICT ON DELETE SET NULL,
    ip_address    TEXT                     NOT NULL,
    source_system TEXT                     NOT NULL,
    version      BIGINT                            DEFAULT 1 NOT NULL,
    date_created TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    date_updated  TIMESTAMP WITH TIME ZONE
);;

CREATE TABLE lms.refresh_tokens (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token             TEXT                     NOT NULL,
    entity_id         BIGINT                   NOT NULL REFERENCES lms.entities ON UPDATE RESTRICT ON DELETE CASCADE,
    login_attempts_id BIGINT                   NOT NULL REFERENCES lms.login_attempts ON UPDATE RESTRICT ON DELETE SET NULL,
    expires_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    version      BIGINT                            DEFAULT 1 NOT NULL,
    date_created TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    date_updated      TIMESTAMP WITH TIME ZONE
);;

CREATE INDEX index_refresh_tokens_user_id ON lms.refresh_tokens (entity_id);;

CREATE TABLE lms.user_roles (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_id    BIGINT                   NOT NULL REFERENCES lms.entities ON UPDATE RESTRICT ON DELETE CASCADE,
    role_id      BIGINT                   NOT NULL REFERENCES lms.roles ON UPDATE RESTRICT ON DELETE RESTRICT,
    version BIGINT DEFAULT 1 NOT NULL,
    date_created TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    date_updated TIMESTAMP WITH TIME ZONE,
    CONSTRAINT unique_user_role UNIQUE (entity_id, role_id)
);;

CREATE INDEX index_user_roles_user_id ON lms.user_roles (entity_id);;
CREATE INDEX index_user_roles_role_id ON lms.user_roles (role_id);;

-- accounts
CREATE TABLE lms.currencies (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code           CHAR(3) UNIQUE           NOT NULL,
    numeric_code   CHAR(3) UNIQUE           NOT NULL,
    name           TEXT                     NOT NULL,
    symbol         TEXT,
    decimal_places SMALLINT                 NOT NULL,
    active         BOOLEAN                  NOT NULL,
    version      BIGINT                            DEFAULT 1 NOT NULL,
    date_created TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    date_updated   TIMESTAMP WITH TIME ZONE
);;

CREATE TABLE lms.account_types (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                   TEXT                     NOT NULL UNIQUE,
    description            TEXT                     NOT NULL,
    parent_account_type_id BIGINT REFERENCES lms.account_types ON UPDATE RESTRICT ON DELETE CASCADE,
    version      BIGINT                            DEFAULT 1 NOT NULL,
    date_created TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    date_updated           TIMESTAMP WITH TIME ZONE
);;

CREATE TABLE lms.account_statuses (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         TEXT                     NOT NULL UNIQUE,
    description  TEXT                     NOT NULL,
    version BIGINT DEFAULT 1 NOT NULL,
    date_created TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    date_updated TIMESTAMP WITH TIME ZONE
);;

CREATE TABLE lms.accounts (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         TEXT                     NOT NULL UNIQUE,
    description  TEXT                     NOT NULL,
    account_type_id   BIGINT                   NOT NULL REFERENCES lms.account_types ON UPDATE RESTRICT ON DELETE CASCADE,
    overdrawable      BOOLEAN                  NOT NULL,
    account_status_id BIGINT                   NOT NULL REFERENCES lms.account_statuses ON UPDATE RESTRICT ON DELETE CASCADE,
    version      BIGINT                            DEFAULT 1 NOT NULL,
    date_created TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    date_updated      TIMESTAMP WITH TIME ZONE
);;

CREATE INDEX index_accounts_account_type_id ON lms.accounts (account_type_id);;

CREATE TABLE lms.account_balances (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id            BIGINT                   NOT NULL REFERENCES lms.accounts ON UPDATE RESTRICT ON DELETE CASCADE,
    currency_id           BIGINT                   NOT NULL REFERENCES lms.currencies ON UPDATE RESTRICT ON DELETE CASCADE,
    balance_minor         BIGINT                   NOT NULL DEFAULT 0,
    upper_threshold_minor BIGINT,
    lower_threshold_minor BIGINT,
    version      BIGINT                            DEFAULT 1 NOT NULL,
    date_created TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    date_updated          TIMESTAMP WITH TIME ZONE,
    CONSTRAINT unique_account_balance UNIQUE (account_id, currency_id)
);;

CREATE INDEX index_account_balances_account_id ON lms.account_balances (account_id);;
CREATE INDEX index_account_balances_currency ON lms.account_balances (currency_id);;

CREATE TABLE lms.partner_accounts (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_id    BIGINT                   NOT NULL REFERENCES lms.entities ON UPDATE RESTRICT ON DELETE CASCADE,
    account_id   BIGINT                   NOT NULL REFERENCES lms.accounts ON UPDATE RESTRICT ON DELETE CASCADE,
    version BIGINT DEFAULT 1 NOT NULL,
    date_created TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    date_updated TIMESTAMP WITH TIME ZONE,
    CONSTRAINT unique_partner_account UNIQUE (entity_id, account_id)
);;

-- transactions
CREATE TABLE lms.reason_types (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         TEXT                     NOT NULL UNIQUE,
    description  TEXT                     NOT NULL,
    version      BIGINT                            DEFAULT 1 NOT NULL,
    date_created TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    date_updated TIMESTAMP WITH TIME ZONE
);;

CREATE TABLE lms.transaction_types (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         TEXT                     NOT NULL UNIQUE,
    description  TEXT                     NOT NULL,
    reversible   BOOLEAN                  NOT NULL,
    version BIGINT DEFAULT 1 NOT NULL,
    date_created TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    date_updated TIMESTAMP WITH TIME ZONE
);;

CREATE TABLE lms.reason_type_transaction_types (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reason_type_id      BIGINT                   NOT NULL REFERENCES lms.reason_types ON UPDATE RESTRICT ON DELETE RESTRICT,
    transaction_type_id BIGINT                   NOT NULL REFERENCES lms.transaction_types ON UPDATE RESTRICT ON DELETE RESTRICT,
    version             BIGINT                            DEFAULT 1 NOT NULL,
    date_created        TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    date_updated        TIMESTAMP WITH TIME ZONE,
    CONSTRAINT unique_reason_type_transaction_types UNIQUE (reason_type_id, transaction_type_id)
);;

CREATE TABLE lms.transaction_types_debit_accounts (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_type_id BIGINT                   NOT NULL REFERENCES lms.transaction_types ON UPDATE RESTRICT ON DELETE RESTRICT,
    account_id          BIGINT                   NOT NULL REFERENCES lms.accounts ON UPDATE RESTRICT ON DELETE RESTRICT,
    version BIGINT DEFAULT 1 NOT NULL,
    date_created        TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    date_updated        TIMESTAMP WITH TIME ZONE,
    CONSTRAINT unique_transaction_type_debit_account UNIQUE (transaction_type_id, account_id)
);;

CREATE TABLE lms.transaction_types_credit_accounts (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_type_id BIGINT                   NOT NULL REFERENCES lms.transaction_types ON UPDATE RESTRICT ON DELETE RESTRICT,
    account_id          BIGINT                   NOT NULL REFERENCES lms.accounts ON UPDATE RESTRICT ON DELETE RESTRICT,
    version BIGINT DEFAULT 1 NOT NULL,
    date_created        TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    date_updated        TIMESTAMP WITH TIME ZONE,
    CONSTRAINT unique_transaction_type_credit_account UNIQUE (transaction_type_id, account_id)
);;

CREATE TABLE lms.transactions (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idempotency_key       TEXT                     NOT NULL UNIQUE,
    transaction_reference TEXT                     NOT NULL UNIQUE,
    transaction_type_id   BIGINT                   NOT NULL REFERENCES lms.transaction_types ON UPDATE RESTRICT ON DELETE RESTRICT,
    opposite_party_id     BIGINT                   NOT NULL REFERENCES lms.entities ON UPDATE RESTRICT ON DELETE RESTRICT,
    linked_transaction_id BIGINT REFERENCES lms.transactions ON UPDATE RESTRICT ON DELETE RESTRICT,
    version               BIGINT                            DEFAULT 1 NOT NULL,
    date_created          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    date_updated          TIMESTAMP WITH TIME ZONE
);;

CREATE TABLE lms.transaction_entries (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_reference TEXT                     NOT NULL UNIQUE,
    transaction_id        BIGINT                   NOT NULL REFERENCES lms.transactions ON UPDATE RESTRICT ON DELETE RESTRICT,
    debit_amount_minor    BIGINT                   NOT NULL,
    credit_amount_minor   BIGINT                   NOT NULL,
    currency              BIGINT                   NOT NULL REFERENCES lms.currencies ON UPDATE RESTRICT ON DELETE RESTRICT,
    account_id            BIGINT                   NOT NULL REFERENCES lms.accounts ON UPDATE RESTRICT ON DELETE RESTRICT,
    account_balance_minor BIGINT                   NOT NULL,
    version BIGINT DEFAULT 1 NOT NULL,
    date_created          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    date_updated          TIMESTAMP WITH TIME ZONE
);;

CREATE TABLE lms.loan_products (
    id                             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                           TEXT                     NOT NULL UNIQUE,
    description                    TEXT                     NOT NULL,
    interest_chargeable            BOOLEAN                  NOT NULL,
    interest_rate                  NUMERIC(5, 4) CHECK (interest_chargeable = FALSE OR interest_rate IS NOT NULL),
    interest_term_unit             lms.TERM_UNIT CHECK (interest_chargeable = FALSE OR interest_term_unit IS NOT NULL),
    access_fee_chargeable          BOOLEAN                  NOT NULL,
    access_fee_percentage          NUMERIC(5, 4),
    term                           INT                      NOT NULL,
    term_unit                      lms.TERM_UNIT            NOT NULL,
    max_disbursements_per_customer INT                      NOT NULL,
    active                         BOOLEAN                  NOT NULL,
    version      BIGINT                            DEFAULT 1 NOT NULL,
    date_created TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    date_updated                   TIMESTAMP WITH TIME ZONE,
    CHECK (access_fee_chargeable = FALSE OR access_fee_percentage IS NOT NULL)
);;

CREATE TABLE lms.loan_product_partners (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    loan_product_id BIGINT                   NOT NULL REFERENCES lms.loan_products ON UPDATE RESTRICT ON DELETE RESTRICT,
    entity_id       BIGINT                   NOT NULL REFERENCES lms.entities ON UPDATE RESTRICT ON DELETE RESTRICT,
    version      BIGINT                            DEFAULT 1 NOT NULL,
    date_created TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    date_updated    TIMESTAMP WITH TIME ZONE,
    CONSTRAINT unique_loan_product_partner UNIQUE (loan_product_id, entity_id)
);;

CREATE TABLE lms.product_reason_types (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    loan_product_id BIGINT                   NOT NULL REFERENCES lms.loan_products ON UPDATE RESTRICT ON DELETE RESTRICT,
    reason_type_id  BIGINT                   NOT NULL REFERENCES lms.reason_types ON UPDATE RESTRICT ON DELETE RESTRICT,
    version         BIGINT                            DEFAULT 1 NOT NULL,
    date_created    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    date_updated    TIMESTAMP WITH TIME ZONE,
    CONSTRAINT unique_product_reason_type UNIQUE (loan_product_id, reason_type_id)
);;

CREATE TABLE lms.loans (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id            BIGINT                   NOT NULL REFERENCES lms.entities ON UPDATE RESTRICT ON DELETE RESTRICT,
    principal_amount_minor BIGINT                   NOT NULL,
    access_fee_minor       BIGINT                   NOT NULL,
    total_amount_minor     BIGINT                   NOT NULL,
    current_balance        BIGINT                   NOT NULL,
    currency               BIGINT                   NOT NULL REFERENCES lms.currencies ON UPDATE RESTRICT ON DELETE RESTRICT,
    due_date               TIMESTAMP WITH TIME ZONE NOT NULL,
    status                 LOAN_STATUS              NOT NULL,
    version                BIGINT                            DEFAULT 1 NOT NULL,
    date_created           TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    date_updated           TIMESTAMP WITH TIME ZONE
);;

CREATE TABLE lms.loan_transactions (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    loan_id               BIGINT                   NOT NULL REFERENCES lms.loans ON UPDATE RESTRICT ON DELETE RESTRICT,
    transaction_id        BIGINT                   NOT NULL REFERENCES lms.transactions ON UPDATE RESTRICT ON DELETE RESTRICT,
    loan_transaction_type TEXT                     NOT NULL CHECK ( loan_transaction_type IN
                                                                    ('DISBURSEMENT', 'REPAYMENT', 'INTEREST',
                                                                     'REVERSAL') ),
    version               BIGINT                            DEFAULT 1 NOT NULL,
    date_created          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    date_updated          TIMESTAMP WITH TIME ZONE
);;

CREATE TABLE lms.loan_repayment_schedules (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    loan_id                 BIGINT                   NOT NULL REFERENCES lms.loans ON UPDATE RESTRICT ON DELETE RESTRICT,
    transaction_id          BIGINT                   NOT NULL REFERENCES lms.transactions ON UPDATE RESTRICT ON DELETE RESTRICT,
    principal_portion_minor BIGINT                   NOT NULL,
    interest_portion_minor  BIGINT                   NOT NULL,
    current_balance         BIGINT                   NOT NULL,
    version                 BIGINT                            DEFAULT 1 NOT NULL,
    date_created            TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    date_updated            TIMESTAMP WITH TIME ZONE
);;

CREATE FUNCTION lms.audit_trigger() RETURNS TRIGGER
    LANGUAGE plpgsql
AS
$$
DECLARE
    new_data   JSONB;
    old_data   JSONB;
    key        TEXT;
    new_values JSONB;
    old_values JSONB;
    user_id    TEXT;
BEGIN

    user_id := CURRENT_SETTING('audit.user_id', TRUE);

    IF user_id IS NULL THEN
        user_id := CURRENT_USER;
    END IF;

    new_values := '{}';
    old_values := '{}';

    IF TG_OP = 'INSERT' THEN
        new_data := TO_JSONB(NEW);
        new_values := new_data;

    ELSIF TG_OP = 'UPDATE' THEN
        new_data := TO_JSONB(NEW);
        old_data := TO_JSONB(OLD);

        FOR key IN SELECT JSONB_OBJECT_KEYS(new_data) INTERSECT SELECT JSONB_OBJECT_KEYS(old_data)
            LOOP
                IF new_data ->> key != old_data ->> key THEN
                    new_values := new_values || JSONB_BUILD_OBJECT(key, new_data ->> key);
                    old_values := old_values || JSONB_BUILD_OBJECT(key, old_data ->> key);
                END IF;
            END LOOP;

    ELSIF TG_OP = 'DELETE' THEN
        old_data := TO_JSONB(OLD);
        old_values := old_data;

        FOR key IN SELECT JSONB_OBJECT_KEYS(old_data)
            LOOP
                old_values := old_values || JSONB_BUILD_OBJECT(key, old_data ->> key);
            END LOOP;

    END IF;

    IF TG_OP = 'INSERT' OR TG_OP = 'UPDATE' THEN
        INSERT INTO lms.audit_log (table_name, record_id, operation_type, changed_by, original_values, new_values)
        VALUES (TG_TABLE_NAME, NEW.id, TG_OP, user_id, old_values, new_values);

        RETURN NEW;
    ELSE
        INSERT INTO lms.audit_log (table_name, record_id, operation_type, changed_by, original_values, new_values)
        VALUES (TG_TABLE_NAME, OLD.id, TG_OP, user_id, old_values, new_values);

        RETURN OLD;
    END IF;
END;
$$;;

CREATE TRIGGER trg_audit_permissions
    AFTER INSERT OR UPDATE OR DELETE
    ON lms.permissions
    FOR EACH ROW
EXECUTE PROCEDURE lms.audit_trigger();;

CREATE TRIGGER trg_audit_roles
    AFTER INSERT OR UPDATE OR DELETE
    ON lms.roles
    FOR EACH ROW
EXECUTE PROCEDURE lms.audit_trigger();;

CREATE TRIGGER trg_audit_role_permissions
    AFTER INSERT OR UPDATE OR DELETE
    ON lms.role_permissions
    FOR EACH ROW
EXECUTE PROCEDURE lms.audit_trigger();;

CREATE TRIGGER trg_audit_id_types
    AFTER INSERT OR UPDATE OR DELETE
    ON lms.id_types
    FOR EACH ROW
EXECUTE PROCEDURE lms.audit_trigger();;

CREATE TRIGGER trg_audit_credential_statuses
    AFTER INSERT OR UPDATE OR DELETE
    ON lms.credential_statuses
    FOR EACH ROW
EXECUTE PROCEDURE lms.audit_trigger();;

CREATE TRIGGER trg_audit_entities
    AFTER INSERT OR UPDATE OR DELETE
    ON lms.entities
    FOR EACH ROW
EXECUTE PROCEDURE lms.audit_trigger();;

CREATE TRIGGER trg_audit_entity_contacts
    AFTER INSERT OR UPDATE OR DELETE
    ON lms.entity_contacts
    FOR EACH ROW
EXECUTE PROCEDURE lms.audit_trigger();;

CREATE TRIGGER trg_audit_entity_ids
    AFTER INSERT OR UPDATE OR DELETE
    ON lms.entity_ids
    FOR EACH ROW
EXECUTE PROCEDURE lms.audit_trigger();;

CREATE TRIGGER trg_audit_entity_credentials
    AFTER INSERT OR UPDATE OR DELETE
    ON lms.entity_credentials
    FOR EACH ROW
EXECUTE PROCEDURE lms.audit_trigger();;

CREATE TRIGGER trg_audit_login_attempts
    AFTER INSERT OR UPDATE OR DELETE
    ON lms.login_attempts
    FOR EACH ROW
EXECUTE PROCEDURE lms.audit_trigger();;

CREATE TRIGGER trg_audit_refresh_tokens
    AFTER INSERT OR UPDATE OR DELETE
    ON lms.refresh_tokens
    FOR EACH ROW
EXECUTE PROCEDURE lms.audit_trigger();;

CREATE TRIGGER trg_audit_user_roles
    AFTER INSERT OR UPDATE OR DELETE
    ON lms.user_roles
    FOR EACH ROW
EXECUTE PROCEDURE lms.audit_trigger();;

CREATE TRIGGER trg_audit_currencies
    AFTER INSERT OR UPDATE OR DELETE
    ON lms.currencies
    FOR EACH ROW
EXECUTE PROCEDURE lms.audit_trigger();;

CREATE TRIGGER trg_audit_account_types
    AFTER INSERT OR UPDATE OR DELETE
    ON lms.account_types
    FOR EACH ROW
EXECUTE PROCEDURE lms.audit_trigger();;

CREATE TRIGGER trg_audit_account_statuses
    AFTER INSERT OR UPDATE OR DELETE
    ON lms.account_statuses
    FOR EACH ROW
EXECUTE PROCEDURE lms.audit_trigger();;

CREATE TRIGGER trg_audit_accounts
    AFTER INSERT OR UPDATE OR DELETE
    ON lms.accounts
    FOR EACH ROW
EXECUTE PROCEDURE lms.audit_trigger();;

CREATE TRIGGER trg_audit_account_balances
    AFTER INSERT OR UPDATE OR DELETE
    ON lms.account_balances
    FOR EACH ROW
EXECUTE PROCEDURE lms.audit_trigger();;

CREATE TRIGGER trg_audit_partner_accounts
    AFTER INSERT OR UPDATE OR DELETE
    ON lms.partner_accounts
    FOR EACH ROW
EXECUTE PROCEDURE lms.audit_trigger();;

CREATE TRIGGER trg_audit_reason_types
    AFTER INSERT OR UPDATE OR DELETE
    ON lms.reason_types
    FOR EACH ROW
EXECUTE PROCEDURE lms.audit_trigger();;

CREATE TRIGGER trg_audit_transaction_types
    AFTER INSERT OR UPDATE OR DELETE
    ON lms.transaction_types
    FOR EACH ROW
EXECUTE PROCEDURE lms.audit_trigger();;

CREATE TRIGGER trg_audit_reason_type_transaction_types
    AFTER INSERT OR UPDATE OR DELETE
    ON lms.reason_type_transaction_types
    FOR EACH ROW
EXECUTE PROCEDURE lms.audit_trigger();;

CREATE TRIGGER trg_audit_transaction_types_debit_accounts
    AFTER INSERT OR UPDATE OR DELETE
    ON lms.transaction_types_debit_accounts
    FOR EACH ROW
EXECUTE PROCEDURE lms.audit_trigger();;

CREATE TRIGGER trg_audit_transaction_types_credit_accounts
    AFTER INSERT OR UPDATE OR DELETE
    ON lms.transaction_types_credit_accounts
    FOR EACH ROW
EXECUTE PROCEDURE lms.audit_trigger();;

CREATE TRIGGER trg_audit_transactions
    AFTER INSERT OR UPDATE OR DELETE
    ON lms.transactions
    FOR EACH ROW
EXECUTE PROCEDURE lms.audit_trigger();;

CREATE TRIGGER trg_audit_transaction_entries
    AFTER INSERT OR UPDATE OR DELETE
    ON lms.transaction_entries
    FOR EACH ROW
EXECUTE PROCEDURE lms.audit_trigger();;

CREATE TRIGGER trg_audit_loan_products
    AFTER INSERT OR UPDATE OR DELETE
    ON lms.loan_products
    FOR EACH ROW
EXECUTE PROCEDURE lms.audit_trigger();;

CREATE TRIGGER trg_audit_loan_product_partners
    AFTER INSERT OR UPDATE OR DELETE
    ON lms.loan_product_partners
    FOR EACH ROW
EXECUTE PROCEDURE lms.audit_trigger();;

CREATE TRIGGER trg_audit_product_reason_types
    AFTER INSERT OR UPDATE OR DELETE
    ON lms.product_reason_types
    FOR EACH ROW
EXECUTE PROCEDURE lms.audit_trigger();;

CREATE TRIGGER trg_audit_loans
    AFTER INSERT OR UPDATE OR DELETE
    ON lms.loans
    FOR EACH ROW
EXECUTE PROCEDURE lms.audit_trigger();;

CREATE TRIGGER trg_audit_loan_transactions
    AFTER INSERT OR UPDATE OR DELETE
    ON lms.loan_transactions
    FOR EACH ROW
EXECUTE PROCEDURE lms.audit_trigger();;

CREATE TRIGGER trg_audit_loan_repayment_schedules
    AFTER INSERT OR UPDATE OR DELETE
    ON lms.loan_repayment_schedules
    FOR EACH ROW
EXECUTE PROCEDURE lms.audit_trigger();;
